[project]
name = "media-news-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agenttoolprotocol>=0.2.5",
    "aiohttp>=3.13.2",
    "bs4>=0.0.2",
    "deep-translator>=1.11.4",
    "duckduckgo-search==6.3.4",
    "fastapi>=0.122.0",
    "huggingface-hub[hf-xet]>=0.36.0",
    "joblib>=1.5.2",
    "langdetect>=1.0.9",
    "lxml>=6.0.2",
    "matplotlib>=3.10.7",
    "mistralai>=1.9.11",
    "newsapi-python>=0.2.7",
    "nltk>=3.9.2",
    "numpy>=2.3.4",
    "openai>=2.9.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "spacy>=3.8.7",
    "streamlit>=1.51.0",
    "uvicorn>=0.38.0",
    "wordcloud>=1.9.4",
    "xgboost>=3.1.2",
]
